name: cnic_detection_tflite
description: "Flutter app for testing YOLOv8n TFLite model"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.2
  path_provider: ^2.1.2
  tflite_flutter:
    git:
      url: https://github.com/tensorflow/flutter-tflite.git
      ref: main
  image: ^4.5.4
  permission_handler: ^12.0.1
  exif: ^3.3.0
  google_ml_kit: ^0.20.0

flutter:
  uses-material-design: true
  assets:
    - assets/best_float32.tflite
    - assets/test.txt
